name: Documentation
on:
  push:
    branches:
      - main
      - more-types

jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2

      - name: "Build docs with JavaDoc"
        run: ./gradlew javadoc --info

      - name: "Publish JavaDoc"
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          publish_dir: 'lib/build/docs/javadoc'
